cargo-lambda/cargo-lambda

Cargo.lock, Cargo.toml, src/main.rs
No need to install `cargo-zigbuild` separately.
=> Integrate `zig cc` directly into `cargo-lambda`

src/main.rs
This will allow us to play nice with other tools, like the AWS-CDK
that have the expectation of controlling output directories.
=> Add an output flag to change the final binary location.

README.md, src/main.rs
=> Make the output format flag case insensitive.

src/main.rs
=> Fix the version flag.

src/build.rs
That way, if you specify a binary that's missing you
don't have to wait until the project compiles to find out.
=> Validate the --bin flag before building

.github/workflows/Release.yml, Cargo.lock, Cargo.toml
=> Release prebuilt binaries on CI

Cargo.lock, Cargo.toml, src/start/mod.rs, src/start/requests.rs, src/start/trace.rs
- Propagate trace ids from the invoke endpoint to functions.
- Integrate with OpenTelemetry-AWS with Tracing.
- Add flag to show traces in the standard output.
Fixes #18 
=> Add support for XRay

.github/workflows/build.yml, Cargo.toml, README.md
Strip symbols from release binaries, so they are smaller.
=> Prepare release 0.5

src/build.rs, src/metadata.rs, test/fixtures/missing-binary-package/Cargo.toml, test/fixtures/multi-binary-package/Cargo.toml, test/fixtures/single-binary-package/Cargo.toml, test/fixtures/workspace-package/Cargo.toml, test/fixtures/workspace-package/crate-1/Cargo.toml, test/fixtures/workspace-package/crate-2/Cargo.toml
Thanks for your help detecting this problem @mbergkvist!
I've picked up your change and added some tests to prevent this from happening again.
I'll release a patch version as soon as all is green.
=> Fix binary metadata

src/build.rs, src/metadata.rs
@calavera 
I did the refactoring you mentioned in #38 before I noticed you'd already merged in my other change.
Your refactoring were almost the same as mine, but I had some smaller changes, they're in this PR if you find them suitable.
=> Refactor leftovers

Cargo.lock, Cargo.toml, src/build.rs, src/command.rs, src/main.rs, src/start/mod.rs, src/start/scheduler.rs, src/toolchain.rs, src/zig.rs
Otherwise all of them fail with `command not found` on Windows.
(cherry picked from commit 0286cd75d23af41670607f23543b738c8c7e48ee)
=> Run commands in new shells on Windows

Cargo.lock, Cargo.toml
=> Release v0.5.2

Cargo.lock, README.md, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-metadata/src/lib.rs
Update repository metadata with the new home.
=> Release 0.6.0

Cargo.lock, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-build/README.md, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-interactive/Cargo.toml, crates/cargo-lambda-interactive/README.md, crates/cargo-lambda-invoke/Cargo.toml, crates/cargo-lambda-invoke/README.md, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-metadata/README.md, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-new/README.md, crates/cargo-lambda-watch/Cargo.toml, crates/cargo-lambda-watch/README.md
=> Publish all subcrates.

.github/workflows/build.yml
=> Run tests on macOS and Windows

Justfile
=> Fix publish-all task.

Cargo.lock, README.md, crates/cargo-lambda-build/src/lib.rs
=> Add a shortcut to build for ARM architectures.

crates/cargo-lambda-watch/src/lib.rs
This way we can expand the API without risk of mixing function names and non function names.
=> Use nested routes for the runtime emulator.

Cargo.lock, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-interactive/Cargo.toml, crates/cargo-lambda-invoke/Cargo.toml, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-watch/Cargo.toml
=> Release v0.6.2

Cargo.lock, crates/cargo-lambda-new/src/lib.rs
Open the project with the editor defined by the environment variable EDITOR.
=> Add --open flag to the `new` command

Cargo.lock, Cargo.toml, README.md, crates/cargo-lambda-build/src/lib.rs, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-cli/src/main.rs, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-deploy/README.md, crates/cargo-lambda-deploy/src/lib.rs, crates/cargo-lambda-interactive/Cargo.toml, crates/cargo-lambda-interactive/src/lib.rs, crates/cargo-lambda-interactive/src/progress.rs, crates/cargo-lambda-invoke/Cargo.toml, crates/cargo-lambda-invoke/src/lib.rs, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-metadata/src/cargo/mod.rs, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-remote/Cargo.toml, crates/cargo-lambda-remote/README.md, crates/cargo-lambda-remote/src/lib.rs, crates/cargo-lambda-watch/Cargo.toml
=> Deploy command

Cargo.lock, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-build/src/lib.rs
=> Update cargo-zigbuild to 0.8.6

Cargo.lock, Justfile, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-interactive/Cargo.toml, crates/cargo-lambda-invoke/Cargo.toml, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-remote/Cargo.toml, crates/cargo-lambda-watch/Cargo.toml
=> Release v0.7.0

Cargo.lock, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-deploy/src/lib.rs
- Wait until configuration changes are fully propagated.
- Don't update configuration when there are no changes.
=> Fix function update

Cargo.lock, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-deploy/Cargo.toml
=> Release v0.7.1

Cargo.lock, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-deploy/src/lib.rs
There are corner cases when it doesn't work as expected.
=> Disable code tagging

crates/cargo-lambda-cli/Cargo.toml
=> Release v0.7.2

Cargo.lock, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-interactive/Cargo.toml, crates/cargo-lambda-invoke/Cargo.toml, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-remote/Cargo.toml, crates/cargo-lambda-watch/Cargo.toml
Fixes compatibility issues with query-map and aws_lambda_events.
=> Release version 0.7.3

Justfile
=> Fix script to publish all crates

crates/cargo-lambda-deploy/src/lib.rs
=> Add layers when deploying a function.

Cargo.lock, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-interactive/Cargo.toml, crates/cargo-lambda-invoke/Cargo.toml, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-remote/Cargo.toml, crates/cargo-lambda-watch/Cargo.toml
=> Release v0.8.0

Justfile
=> Make publish cli one command

crates/cargo-lambda-metadata/src/cargo/mod.rs
Otherwise we always show a warning.
=> Ingore missing metadata.

README.md
=> Add more installation instructions

.github/workflows/release.yml
=> Add flags to build on Windows ARM64.

.github/workflows/release.yml
=> Fix platform key to compile ring.

crates/cargo-lambda-watch/src/trace.rs
=> Remove unused import.

.github/workflows/build.yml, .gitignore, test/fixtures/single-binary-package/Cargo.toml, test/fixtures/single-binary-package/src/main.rs
Verify that building binaries work on all platforms.
=> Add integration tests

.github/actions/choco/Dockerfile, .github/actions/choco/action.yml, .github/actions/choco/entrypoint.sh, .github/workflows/release.yml, .gitignore, README.md, cargo-lambda.nuspec
=> Add action to release Chocolatey packages

.github/workflows/release.yml
=> Fix conditional deploy to Chocolatey

Cargo.lock, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-deploy/Cargo.toml
=> Release version 0.8.1

.github/workflows/release.yml
=> Fix working directory for releases.

.github/workflows/release.yml
=> Fix literal comparison.

.github/workflows/release.yml
Format Get-FileHash output in poweshell.
=> Make the sha file format consistent

.github/actions/choco/entrypoint.sh, .github/workflows/release.yml
=> Release choco binary after all release artifacts are uploaded.

.github/workflows/release.yml, crates/cargo-lambda-cli/Cargo.toml
=> Update CLI version.

.github/workflows/release.yml, crates/cargo-lambda-cli/Cargo.toml
Publish binary with the right version.
=> Release version 0.8.2

.github/workflows/release.yml
=> Fix choco action checkout.

.github/workflows/format.yml, Justfile, crates/cargo-lambda-watch/src/runtime_router.rs, crates/cargo-lambda-watch/src/trace.rs, crates/cargo-lambda-watch/src/trigger_router.rs, rustfmt.toml
=> Fix consistent formatting.

crates/cargo-lambda-watch/src/runtime/extensions_router.rs
The Rust runtime expects a JSON payload in the response.
Fixes https://github.com/awslabs/aws-lambda-rust-runtime/issues/922
=> fix: Return JSON object for extension registration.

crates/cargo-lambda-cli/src/main.rs
=> chore: Reorganize enum.

crates/cargo-lambda-build/src/lib.rs, crates/cargo-lambda-cli/tests/cargo_lambda.rs
In workspaces, zipping all binaries can take a while. This reduces the build time by not zipping all of them when it's not necessary.
Fixes #682
=> fix: Only zip files specified with `--bin` when the flag is present

Cargo.lock, crates/cargo-lambda-build/src/archive.rs, crates/cargo-lambda-cli/tests/harness/mod.rs, crates/cargo-lambda-cli/tests/harness/project.rs, crates/cargo-lambda-new/Cargo.toml, crates/cargo-lambda-new/src/lib.rs, crates/cargo-lambda-new/src/template.rs, docs/commands/new.md
Allow to start with templates that are in a private git repository.
Assume that credentials are properly configured in the machine's git credentials helper.
=> feat(new): Private templates with Git

crates/cargo-lambda-cli/tests/cargo_lambda.rs, crates/cargo-lambda-new/src/lib.rs, crates/cargo-lambda-new/src/template/config.rs, docs/commands/new.md, tests/templates/config-template/CargoLambda.toml, tests/templates/config-template/template/render-test.json
Add a new configuration option in CargoLambda.toml to control template file rendering:
- Add ignore_conditional_files to conditionally ignore files based on prompt variables
=> feat(new): add support for conditional file ignoring in templates

crates/cargo-lambda-new/src/extensions.rs, crates/cargo-lambda-new/src/functions.rs
Update the URLs where function and extension templates are downloaded from.
=> feat(new): Use new templates by default.

crates/cargo-lambda-build/src/archive.rs
Don't fail the build if you cannot set the time. Prefer builds with different checksums than no builds at all.
=> fix(build): Best effort to set the zip file last modified time.

crates/cargo-lambda-watch/src/state.rs
If to use the tool in a mode with standalone Lambda API like running the bellow command separately:
```
cargo lambda watch --only-lambda-apis
```
And after that start a lambda function itself with set of `AWS_LAMBDA_*` env vars.
In this case I see 100% cpu load on a one core and a high flood traffic between the Lambda and the API server like bellow:
```
##
T ::1:40730 -> ::1:9000 [AP] #8
GET /.rt/2018-06-01/runtime/invocation/next HTTP/1.1..user-agent: aws-lambda-rust/0.11.1..host: [::]:9000....                                              
##
T ::1:9000 -> ::1:40730 [AP] #10
HTTP/1.1 204 No Content..lambda-runtime-aws-request-id: d726a21d-9caf-4584-b7e9-de1bbc630bd6..lambda-runtime-deadline-ms: 600000..lambda-runtime-invoked-fu
nction-arn: function-arn..vary: origin, …
```
=> fix: request stack needs to be initialized on lambda connection

crates/cargo-lambda-deploy/src/functions.rs, crates/cargo-lambda-metadata/src/cargo/deploy.rs
Add the option to configure IPv6 dual stack on the function VPC.
Fixes #730 .
=> feat(deploy): Allow to configure VPC Ipv6AllowedForDualStack.

crates/cargo-lambda-deploy/src/dry.rs, crates/cargo-lambda-deploy/src/lib.rs
Add information about the function configuration to the dry output.
=> fix(deploy): Add missing function config information to the dry output.

Cargo.lock, Cargo.toml, crates/cargo-lambda-build/Cargo.toml, crates/cargo-lambda-build/src/archive.rs, crates/cargo-lambda-cli/tests/cargo_lambda.rs, crates/cargo-lambda-deploy/Cargo.toml, crates/cargo-lambda-deploy/src/extensions.rs, crates/cargo-lambda-deploy/src/functions.rs, crates/cargo-lambda-deploy/src/lib.rs, crates/cargo-lambda-deploy/src/roles.rs, crates/cargo-lambda-metadata/src/cargo/deploy.rs, crates/cargo-lambda-metadata/src/lambda.rs, crates/cargo-lambda-remote/Cargo.toml
Add tests that verify that the basic functionality remains working as expected.
=> chore(deploy): Add mock tests using the SDK test utils.

Cargo.lock, Makefile, crates/cargo-lambda-cli/src/main.rs, crates/cargo-lambda-deploy/src/functions.rs, crates/cargo-lambda-deploy/src/lib.rs, crates/cargo-lambda-metadata/Cargo.toml, crates/cargo-lambda-metadata/src/cargo/deploy.rs, crates/cargo-lambda-metadata/tests/jail.rs
Ensure that the base environment is always loaded, even if there are not config env options.
=> fix(deploy): Fix loading the lambda environment.

crates/cargo-lambda-metadata/src/cargo/watch.rs, crates/cargo-lambda-metadata/src/config.rs, crates/cargo-lambda-watch/src/trigger_router.rs, docs/commands/watch.md
=> fix(watch): Propagate path parameters from custom router.

Cargo.lock, crates/cargo-lambda-cli/Cargo.toml, crates/cargo-lambda-cli/tests/cargo_lambda.rs, crates/cargo-lambda-cli/tests/harness/mod.rs, crates/cargo-lambda-metadata/src/cargo/deploy.rs, tests/fixtures/workspace-package/crate-3/Cargo.toml
Tests that verify that the behaviors described in #781 are working as expected.
=> chore(test): Add more tests for deploy configs.

.github/workflows/release.yml, crates/cargo-lambda-cli/pyproject.toml
The current version doesn't work with the 2024 edition.
=> chore(release): Update maturin version.

crates/cargo-lambda-metadata/src/cargo/deploy.rs, tests/fixtures/workspace-package/crate-3/Cargo.toml
Add field to the serializer functions.
=> fix(deploy): Fix log retention serializer.

Cargo.lock, crates/cargo-lambda-build/src/zig.rs, crates/cargo-lambda-cli/src/main.rs, crates/cargo-lambda-metadata/src/cargo/deploy.rs, crates/cargo-lambda-metadata/src/cargo/watch.rs, crates/cargo-lambda-metadata/src/config.rs, crates/cargo-lambda-metadata/src/lambda.rs, crates/cargo-lambda-system/Cargo.toml, crates/cargo-lambda-system/src/lib.rs, docs/commands/system.md
This allows to use the configuration in actions against a project, for example reading the watching custom routes and using them to configure an API Gateway.
=> feat(system): Print the full static configuration in the project.

crates/cargo-lambda-system/src/lib.rs
Consistent with the same flag in the deploy command.
=> fix(system): Make the json output pretty by default.

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/format.yml, .github/workflows/release.yml, .github/workflows/test-docker.yml, .github/workflows/test-docs.yml, CONTRIBUTING.md, Cargo.lock, Cargo.toml, Makefile, crates/cargo-lambda-deploy/src/functions.rs, crates/cargo-lambda-deploy/src/lib.rs, crates/cargo-lambda-metadata/src/cargo/deploy.rs, crates/cargo-lambda-metadata/src/cargo/watch.rs, crates/cargo-lambda-system/Cargo.toml, crates/cargo-lambda-system/src/lib.rs, deny.toml, docs/guide/configuration.md
- Remove unnecessary dependencies.
- Update serde configuration to prevent flattenning of empty structs.
- Update docs.
fixes #824
=> fix(system): Fix system output format.

crates/cargo-lambda-system/src/lib.rs
Print only the Zig information, ignore config if a manifest file is not present.
=> fix(system): Allow to run system subcommand without a project.

Cargo.lock, Cargo.toml, crates/cargo-lambda-build/src/compiler/cargo_zigbuild.rs, crates/cargo-lambda-build/src/zig.rs, crates/cargo-lambda-system/src/lib.rs, docs/guide/installation.md
Run the installer automatically when there is only one option.
=> fix(system): Fix issue running the zig installer.

crates/cargo-lambda-build/src/error.rs, crates/cargo-lambda-build/src/zig.rs
=> fix: Improve the messaging when no zig installers are available.

docs/index.md
=> Fix docs typo
