cargo-lambda/cargo-lambda

- Cargo.toml
- src/main.rs
Box the Lambda variant so the enum is not super big.
> Fix the size of the App enum

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
Zip can now be selected as an output format, the compiled binary will be zipped up which can be directly uploaded to create an AWS Lambda function.
The `--output-format` paramters controls the output format, the two
current options are `Zip` and `Binary` with `Binary` being the default.
Example usage to create a bootstrap zip.
```
cargo lambda build --output-format Zip
```
> feat: adding zip as an output

- .github/workflows/build.yml
- .github/workflows/format.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/invoke.rs
- src/main.rs
- src/progress.rs
- src/start.rs
- src/zig.rs
This commands allow people to work locally with
their lambda functions by emulating the Lambda control plane API.
They use cargo-watch to hot reload the function code while
you work in it.
Fixes #5 
> Start and Invoke subcommands

- Cargo.lock
- Cargo.toml
Cargo doesn't allow you to publish crates with git dependencies.
Use my own published fork until changes are merged and released
upstream.
> Use my published fork

- Cargo.lock
- Cargo.toml
- README.md
- src/build.rs
- src/main.rs
- src/metadata.rs
- src/start/mod.rs
- src/start/scheduler.rs
Use the package.metadata section in Cargo.toml to provide
environment variables.
Fixes #23 
> Support environment variables.

- .github/workflows/build.yml
Otherwise GitHub doesn't try to run workflows for forks.
> Bring back pull_request events

- src/build.rs
I found a minor bug when doing local testing with a `cargo install --path .` approach: if I pass a target along with glibc version like `x86_64-unknown-linux-musl.2.17`, it tries to install the target component as it includes glibc part when checking if it's installed in the toolchain. Ideally, it should exclude the part after `.` in the final target which we run checks against.
These changes should fix following issues:
* when determining same target as host, use `starts_with` instead, in case `--target` has a trailing glibc part
* when checking if target is installed in toolchain, use the target name before the `.`, so we can omit the glibc part in the check
> fix: ignore glibc version in `--target` for checks

- Cargo.lock
- README.md
- crates/cargo-lambda-invoke/src/lib.rs
- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/src/scheduler.rs
For packages that only include one function in the package's
main.rs file, we can compile the code without --bin and give
the function a default name that's not a valid cargo binary name.
> Allow running `invoke` without a function name

- Cargo.lock
- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/scheduler.rs
- crates/cargo-lambda-watch/src/watch_installer.rs
Fallback to cargo install for other platforms that we don't
know that cargo-watch is compiled statically.
Fixes #46 
> Download cargo-watch from releases for known platforms.

- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/src/watch_installer.rs
Make sure the file names are correct.
Use conditional compilation to include less dependencies.
> Fix cargo-watch installation on Windows

- README.md
- crates/cargo-lambda-cli/src/main.rs
- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/scheduler.rs
This pull request includes several suggestions to support #54:
- Change 'watch' subcommand to 'runtime' to better represent what it does. (emulates a runtime)
- Add 'watch' as a flag for runtime. (default is false)
- Since this is a breaking change the version was bumped to 0.6.0.
- Because this is not backwards-compatible aliasing to "start" and "watch" have been removed.
The logic behind making watch default to false, instead of a ''--no-watch" flag is this seems to align with other CLIs.
If instead we support a "--no-watch" flag then aliasing can still remain, but obviously command name needs to change, and watch as a command would be pretty silly to support as you can run
```bash
cargo lambda watch --no-watch
```
and get something valid. Start would still be ok but wouldn't behave as …
> Feature: add ```--no-reload``` flag

- crates/cargo-lambda-cli/Cargo.toml
Otherwise `cargo publish` fails.
> Speficy subcrates version.

- .github/workflows/build.yml
- Justfile
- README.md
- crates/cargo-lambda-build/Cargo.toml
- crates/cargo-lambda-build/README.md
- crates/cargo-lambda-cli/Cargo.toml
- crates/cargo-lambda-interactive/Cargo.toml
- crates/cargo-lambda-interactive/README.md
- crates/cargo-lambda-invoke/Cargo.toml
- crates/cargo-lambda-invoke/README.md
- crates/cargo-lambda-metadata/Cargo.toml
- crates/cargo-lambda-metadata/README.md
- crates/cargo-lambda-new/Cargo.toml
- crates/cargo-lambda-new/README.md
- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/README.md
- Set the minimum required Rust version.
-- This fixes installation messages because of compilation errors
on older versions of Rust.
- Run tests with the minimum and also the stable Rust versions.
Fixes #64
> Release 0.6.1

- crates/cargo-lambda-metadata/src/fs/rename_linux.rs
io::ErrorKind::Other no longer gets returned by std as of https://github.com/rust-lang/rust/pull/85746
In lieu of requiring the io_error_more feature, match against the raw_os_error directly
Fixes https://github.com/cargo-lambda/cargo-lambda/issues/70
> rename no longer uses io::ErrorKind::Other

- README.md
- crates/cargo-lambda-build/src/lib.rs
SAM and the CDK use arm_64 as identifiers. Follow this convention.
> Update arm flag to match the name in other tools.

- Cargo.lock
- README.md
- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/requests.rs
- crates/cargo-lambda-watch/src/runtime_router.rs
- crates/cargo-lambda-watch/src/trigger_router.rs
Lambda just launched a feature that allows you to reach
HTTP functions via unique URLs.
The payload that those functions receive are from Api Gateway V2 events.
This change adds support for a similar functionality, using
subpaths instead of subdomains.
> Support for Lambda Function URLs

- crates/cargo-lambda-build/Cargo.toml
- crates/cargo-lambda-cli/Cargo.toml
- crates/cargo-lambda-deploy/Cargo.toml
- crates/cargo-lambda-invoke/Cargo.toml
- crates/cargo-lambda-new/Cargo.toml
- crates/cargo-lambda-watch/Cargo.toml
This makes it easier to ensure that published crates have all the expected internal versions.
> Pin internal dependencies.

- Cargo.lock
- README.md
- crates/cargo-lambda-build/src/lib.rs
- crates/cargo-lambda-deploy/Cargo.toml
- crates/cargo-lambda-deploy/src/extensions.rs
- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-deploy/src/lib.rs
- crates/cargo-lambda-invoke/src/lib.rs
- crates/cargo-lambda-remote/Cargo.toml
- crates/cargo-lambda-remote/src/lib.rs
Adds a new flag to the `build` and `deploy` commands to work with extensions.
Adds a flag to the `deploy` command to print the output in different formats.
> Build & Deploy Lambda extensions

- .github/workflows/release.yml
> Disable windows arm build

- README.md
I've published new packages, and the workflow is working now.
> Remove warning about pypi installation

- crates/cargo-lambda-build/src/lib.rs
- crates/cargo-lambda-build/src/target_arch.rs
According to https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/foundation-arch.md and https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/doc_source/runtimes-avx2.md we can set these target-cpu settings.
I introduced a small refactoring so it's easier to encapsulate the architecture parsing.
Is cargo-lambda meant to work with both `provided.al2` AND `provided`? I'm not sure what assumptions can be made about `provided`
> Compile with target-cpu for more optimizations

- Cargo.lock
- crates/cargo-lambda-invoke/Cargo.toml
- crates/cargo-lambda-invoke/src/lib.rs
Some Windows antiviruses think that if your binary contains
raw.githubusercontent.com inside it, it's a virus.
> Change example download endpoint.

- crates/cargo-lambda-build/src/lib.rs
Allows to put a `bootstrap` file in the root of the output directory.
> Add flatten option

- README.md
Include Scoop for windows.
Link to each installer's homepage.
> Add more installer instructions.

- crates/cargo-lambda-build/src/lib.rs
currently the binary that is written into the zip is written with 0644 permissions, we need to make sure it's set to 0755 so that the environment can execute the binary
> set binary as executable

- Cargo.lock
- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/src/lib.rs
this allows us to ignore files that are declared in a `.gitignore` file in a parent directory.  an example of this is in the [aws-lambda-rust-runtime](https://github.com/awslabs/aws-lambda-rust-runtime) crate, where the root crate's `.gitignore` file ignores all `target/` directories so that crates in the `examples/` directory need not ignore the target themselves.
> discover ignore files from parent origins

- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/scheduler.rs
> fix: Allow `--no-default-features` in `cargo lambda watch`

- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/scheduler.rs
This way you can run binaries that are in different packages.
Fixes #670
> fix: expose `--package` in `cargo lambda watch`

- crates/cargo-lambda-build/src/archive.rs
- crates/cargo-lambda-build/src/lib.rs
- crates/cargo-lambda-deploy/src/lib.rs
- crates/cargo-lambda-metadata/src/cargo.rs
- docs/commands/deploy.md
Use `DESTINATION:SOURCE` to change the destination where files are included in the zip file when you use the option `--include` in the build and deploy commands.
Fixes #685
> feat: Allow changing include destination.

- docs/commands/build.md
This PR adds a documentation update to help users resolve the issue of cargo lambda not finding the Zig installation path when using Pip3 on Windows/WSL environments. It addresses the problem described in the closed issue #678, where Zig is installed but not added to the system’s PATH, leading to build failures.
The documentation now includes steps for users to manually add the Zig installation directory to their PATH in ~/.bashrc, ensuring that cargo lambda can find Zig in future terminal sessions.
This update aims to help users avoid this issue by providing clear instructions on how to configure their environment correctly.
> Add documentation for adding Zig to PATH on Windows/WSL

- .github/workflows/build.yml
- .github/workflows/release.yml
- crates/cargo-lambda-cli/tests/cargo_lambda.rs
- crates/cargo-lambda-new/src/lib.rs
- crates/cargo-lambda-new/src/template/config.rs
- docs/commands/new.md
- tests/templates/config-template/CargoLambda.toml
- tests/templates/config-template/template/render-test.json
Add two new template features to improve flexibility:
1. Conditional file rendering based on prompt variables, allowing template authors to include/exclude files based on user input during project creation via `render_conditional_files` in CargoLambda.toml
2. Template-based path rendering, enabling dynamic file paths using Liquid variables (e.g., "{{ci_provider}}/workflows/build.yml")
- Add RenderCondition struct to handle conditional file logic
- Add render_path_with_variables function for path templating
- Update template config parsing to support both features
- Add tests for both conditional files and path rendering
- Update documentation with examples of both features
> feat(new): add conditional files and template path rendering

- crates/cargo-lambda-new/src/extensions.rs
It's common to attach an events processor to logs and telemetry extensions.
> bug(new): Allow processing events in logs and telemetry extensions

- crates/cargo-lambda-invoke/src/lib.rs
Allow people to pass the full file name and other combinations.
> chore(invoke): Relax example name format.

- crates/cargo-lambda-deploy/src/roles.rs
Fixes part of: https://github.com/cargo-lambda/cargo-lambda/issues/724
When using `cargo lambda deploy` it creates a lambda execution role using your current credentials and then verifies it can assume it. If the current credentials have a SourceIdentity, it requires `sts:SetSourceIdentity` in the trust policy of the role so that it can propagate the SourceIdentity when it assumes the role.  This change adds that permission and then removes it once the role is successfully tested.  I tested this locally using credentials that had a SourceIdentity and it deployed successfully. I also verified the trust policy was successfully modified to be:
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": {
"Service": "lambda.amazonaws.com"
},
"Action": "sts:AssumeRole"
}
] …
```
> Add support for credentials with a SourceIdentity

- crates/cargo-lambda-metadata/src/cargo.rs
- crates/cargo-lambda-watch/src/lib.rs
- docs/commands/watch.md
When you specify the option `--package` with the watch command, Cargo starts watching only one package in your workspace. However, Cargo Lambda doesn't take that into account to create the Function URLs routing.
With this change, the specific package is filtered to create the function router, allowing you to use the root path for your function even if your workspace has more binary packages that you're not watching.
Fixes #707
> fix(watch): Filter packages for routing.

- crates/cargo-lambda-build/src/target_arch.rs
You can build x86_64 binaries from ARM64 and viceversa.
Fixes #734
> fix(build): Relax static linking on Linux.

- Cargo.lock
- crates/cargo-lambda-watch/Cargo.toml
- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/watcher.rs
- crates/cargo-lambda-watch/src/watcher/ignore.rs
Create multiple filters to ensure that a wildcard in a subdirectory doesn't affect the matching of predefined filter, like ignoring the `target` directory.
Fixes #669
> fix(watch): Fix ignore matcher for wildcards in children directories.

- Makefile
Metadata depends on structs in Remote now.
> fix: Fix publishing order.

- Cargo.lock
- crates/cargo-lambda-build/src/archive.rs
- crates/cargo-lambda-cli/Cargo.toml
- crates/cargo-lambda-cli/tests/cargo_lambda.rs
- crates/cargo-lambda-deploy/Cargo.toml
- crates/cargo-lambda-deploy/src/dry.rs
- crates/cargo-lambda-deploy/src/extensions.rs
- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-deploy/src/lib.rs
With the configuration refactor, extra files are added when the zip file is created the first time. With removes the need to opening the zip file and adding the extra files later.
Fixes #755
> fix(deploy): Remove double extra file insertion.

- Cargo.lock
- Cargo.toml
- crates/cargo-lambda-build/Cargo.toml
- crates/cargo-lambda-build/src/archive.rs
- crates/cargo-lambda-build/src/lib.rs
- crates/cargo-lambda-deploy/src/dry.rs
- crates/cargo-lambda-deploy/src/extensions.rs
- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-deploy/src/lib.rs
This add information about when the deploy you're uploading to AWS was compiled last. It can help users known when they're deploying an binary that has not been compiled in a while.
Fixes #743
> feat(deploy): Add compilation information to the deploy outputs.

- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-metadata/src/cargo/deploy.rs
- Ignore VPC configuration that doesn't have any changes from the default.
- Handle the different combinations of state and update status correctly.
Fixes #759
> fix(deploy): Update state machine to handle state correctly.

- Cargo.lock
- crates/cargo-lambda-new/Cargo.toml
Bump the gix dependency to address
[CVE-2025-22620](https://nvd.nist.gov/vuln/detail/CVE-2025-22620).
> chore: Bump gix dependency

- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-metadata/src/cargo/deploy.rs
- crates/cargo-lambda-remote/src/lib.rs
- docs/commands/deploy.md
- docs/commands/invoke.md
Allow to set a description for each deployed version, so you can add additional context to a release.
Fixes #777
> feat(deploy): Add a description flag for deployed versions.

- Cargo.toml
> chore: Enable LTO and codegen-units.

- crates/cargo-lambda-metadata/src/cargo/watch.rs
-p is used by Cargo for the packages flag.
Fixes #791 
This is going to be a breaking change unfortunately. The `-p` flag comes from the `cargo-options` crate and cannot be modified 😢 .
> fix(watch): Rename shortcut for watch port.

- crates/cargo-lambda-build/src/lib.rs
- crates/cargo-lambda-metadata/src/cargo/mod.rs
- tests/fixtures/workspace-package/Cargo.toml
Always read the release profile info from the workspace manifest since it's the only one that Cargo cares about regardless of where you execute the build command.
Fixes #790
> fix(build): Correctly override release profile.

- Cargo.lock
- Cargo.toml
- crates/cargo-lambda-deploy/Cargo.toml
- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-metadata/src/cargo/deploy.rs
- docs/commands/deploy.md
This call creates the log group if it doesn't exist, and updates the retention policy if the group exists already.
Fixes #799
> feat(deploy): Add an option to change the log retention policy.

- crates/cargo-lambda-cli/tests/cargo_lambda.rs
- crates/cargo-lambda-metadata/src/cargo/deploy.rs
- crates/cargo-lambda-metadata/src/config.rs
- crates/cargo-lambda-metadata/src/error.rs
- crates/cargo-lambda-metadata/src/lambda.rs
- crates/cargo-lambda-metadata/tests/jail.rs
Use a custom parser because clap cannot downcast the Memory struct into i32.
Fixes #810
> fix(deploy): Fix memory value parser.

- Cargo.toml
- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/state.rs
- crates/cargo-lambda-watch/src/trigger_router.rs
#815 
Add `only-lambda-apis` flag to `RuntimeState` and to `is_default_function_enabled` assessment
This allows the default Lambda function functionality to work for `--only-lambda-apis`
> Fix issue described in #815

- Cargo.lock
- crates/cargo-lambda-remote/Cargo.toml
This PR updates rustls-platform-verifier to 0.5 as 0.4 has a breaking issue with the new rustls verions that prevents cargo lambda to be compiled in Linux.
refferences: 
- https://github.com/rustls/rustls/issues/2386
- https://github.com/rustls/rustls-platform-verifier/issues/164
> update rustls-platform-verifier to version 0.5.1

- crates/cargo-lambda-build/src/toolchain.rs
- crates/cargo-lambda-build/src/zig.rs
- crates/cargo-lambda-interactive/src/command.rs
This allows the cli to return an error and print useful information.
> fix(system): Return outputs when a command fails.

- crates/cargo-lambda-build/src/zig.rs
This will also show any arguments that we use, like when it's invoked via python.
> fix(system): Print zig's full command.

- crates/cargo-lambda-cli/tests/cargo_lambda.rs
- crates/cargo-lambda-deploy/src/dry.rs
- crates/cargo-lambda-deploy/src/lib.rs
- crates/cargo-lambda-metadata/src/cargo/deploy.rs
- crates/cargo-lambda-remote/src/lib.rs
Change them to be inside their own fields, since they're not flattened in the Serde structs.
Fixes #839
> fix(deploy): Fix the serializer for remote and vpc configurations.

- .github/workflows/build.yml
- crates/cargo-lambda-metadata/src/env.rs
- crates/cargo-lambda-watch/src/lib.rs
- crates/cargo-lambda-watch/src/watcher/ignore.rs
- docs/commands/watch.md
Ignore patterns from files in system directories with the `cargo-lambda` app name.
Ignore patterns from a `.cargolambdaignore` file in the root of the repository.
Ignore patterns from a file specified with the CARGO_LAMBDA_IGNORE_FILE environment variable.
Fixes #844
> fix(watch): Correct logic to ignore files.

- Cargo.lock
- Cargo.toml
Updating to 0.20.0 fixes an error on Rust nightly on Linux: [#334](https://github.com/rust-cross/cargo-zigbuild/pull/334)
> Update `cargo-zigbuild` to `0.20.0`

- crates/cargo-lambda-watch/src/runtime/mod.rs
fixes: #848 
Currently, `cargo lambda watch` only exposes extension API routes for 'bare' endpoints that don't have function names in them, ie:
```
/2020-01-01/extension/register
/2020-01-01/extension/event/next
```
Meanwhile, when an internal extension (running in the same process as the primary function) makes API calls, it is prefixed with the function name, ie:
```
/_/2020-01-01/extension/register
/_/2020-01-01/extension/event/next
```
This causes any function-scoped extension calls to fall through to fallback handlers and error. In practice, this results in the function hanging on extension registration and the function never exiting the init phase.
This problem was alluded to when internal extension support was first added to the `aws-lambda-rust-runtime`: …
> fix: watch: add missing extension API endpoints for internal extension calls from inside functions

- docs/guide/getting-started.md
List of changes:
- Setup Zig using [`mlugg/setup-zig`](https://github.com/mlugg/setup-zig) (maintained by Zig core team) instead of [`korandoru/setup-zig`](https://github.com/korandoru/setup-zig) (archived).
- Setup Rust and install Cargo Lambda with a single action using [`moonrepo/setup-rust`](https://github.com/moonrepo/setup-rust). This action alone combines the functionalities of 3 distinct actions (setup toolchain + install binaries + manage caching).
> Update GitHub Actions section in `getting-started.md`

- docs/guide/getting-started.md
> fix typo in `getting-started.md`

- crates/cargo-lambda-invoke/src/lib.rs
- crates/cargo-lambda-metadata/src/cargo/watch.rs
Currently, a couple of the short options for the `invoke` subcommand are in conflict.
Just to be sure, I went through all the subcommand short options to see if there were any others:
 Option | `build` | `deploy` | `watch` | `init` | `invoke` | `new` | `system`
-- | -- | -- | -- | -- | -- | -- | --
`-a` | — | `alias` | `invoke-address` | — | ⛔️ `invoke-address` / `alias` | — | —
`-c` | `compiler` | — | — | — | — | — | —
`-h` | `help` | `help` | `help` | `help` | `help` | `help` | `help`
`-i` | `include` | `include` | — | — | — | — | —
`-j` | `jobs` | — | `jobs` | — | — | — | —
`-l` | `lambda-dir` | `lambda-dir` | — | — | — | — | —
`-m` | — | — | — | — | — | — | `manifest-path`
`-o` | `output-format` | `output-format` | — | `open` | `output-format` | `open` | `output-format`
`-p` | …
> Fix conflicting short options

- Cargo.lock
- crates/cargo-lambda-deploy/Cargo.toml
- crates/cargo-lambda-deploy/src/functions.rs
- crates/cargo-lambda-deploy/src/roles.rs
- crates/cargo-lambda-metadata/src/cargo/deploy.rs
- crates/cargo-lambda-remote/Cargo.toml
- crates/cargo-lambda-remote/src/lib.rs
to have better overview in the [AWS Resource Explorer](https://resource-explorer.console.aws.amazon.com/resource-explorer/home?region=eu-central-1#/home) what resources was created by the cargo-lambda, I'm adding tags for the iam role created during deploy
here is how it works:
1. deploy with tags
```sh
❯ cargo lambda deploy --tags cargo:service-name=s3-to-sns
✅ function deployed successfully 🎉
🛠️  binary last compiled 2 days ago
🔍 arn: arn:aws:lambda:eu-central-1:<REDACTED>:function:s3-to-sns
🎭 version: 3
```
2. the role tags
> fix(deploy): allow to set iam role tags when created

- crates/cargo-lambda-deploy/src/dry.rs
- crates/cargo-lambda-deploy/src/extensions.rs
- crates/cargo-lambda-deploy/src/functions.rs
It just kind of bugged me that we had one more whitespace there compared to the other informations. 😄
> chore: fixed whitespaces
